CREATE DATABASE IF NOT EXISTS AmazingPakistan;
use AmazingPakistan;

CREATE TABLE  IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS famous_places(
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    para LONGTEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS northern_areas(
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    para LONGTEXT NOT NULL
);


INSERT INTO famous_places (name, image, para) VALUES
('Badshahi Mosque', 'SKU001.jpg','Badshahi Mosque, Lahore me waqia, duniya ki sab se bari aur mashhoor masajid me se aik hai. Yeh masjid 1673 me Mughal Shahenshah Aurangzeb ne tameer karwai thi aur Mughal fun-e-taamir ki shan o azmat ki alamat hai. Masjid ka bara sahn, shandaar surkh patthar ki deewarain, aur nafees sang-e-marmar ki kaarigari dekhne walon ko mashoor kar deti hai. Minar, gumbad aur darwazon par ki gayi barik naqashi aur tafseeli aaraish masjid ki khoobsurti ko barhati hai. Sadiyon se ibadat aur saqaafati taqreebat ka markaz rahi, yeh masjid aaj bhi sayahon, morakheen aur mazhabi aqeedat rakhne walon ko apni taraf khenchti hai. Yahan ki pursukoon fiza aur tareekhi ahmiyat ise Lahore ki sab se numaya aur Pakistani saqaafat ki alamat banati hai.'),
('Minar-e-Pakistan', 'SKU002.jpg','Minar-e-Pakistan, jo Lahore ke Iqbal Park me waqia hai, Pakistan ki tareekh ka aik bohot ahem aur qabil-e-ehtram yaadgar hai. Yeh woh maqam hai jahan 1940 me Lahore Resolution manzoor hui, jisne Pakistan ke qiyam ki bunyaad rakhi. Minar ki tameer me Islami, Mughal aur modern fun-e-taamir ka haseen imtizaj dekha ja sakta hai. Is ke gird khoobsurat bagh, fawaray aur paidal raste hain jahan log a kar tareekh par ghour karte hain. Har saal lakhon afrad yahan aate hain taake Pakistan ki tareekh aur qurbaniyon ko yaad rakhein aur is qaumi yaadgar ki azmat mehsoos karein.'),
('Lahore Fort', 'SKU003.jpg','Lahore Fort, jo UNESCO World Heritage Site hai, Mughal dor ki shandar fun-e-taamir aur shahenshahi shan ka aaina hai. Is me shandaar mahal, haveliyan, pavilions aur khoobsurat bagh shamil hain, jo mukhtalif shahenshahoon ki tameerati kala ka shahkar hain. Mashhoor imaratein jaise Sheesh Mahal, Naulakha Pavilion aur Alamgiri Gate nafees sang-e-marmar ki kaarigari aur barik naqashi ko dikhati hain. Fort me museums bhi hain jo Mughal dor ke asnaad, artifacts aur tareekhi cheezon ko mehfooz karte hain. Tourists, historians aur culture enthusiasts yahan aate hain taake architecture, history aur cultural significance ka lutf utha saken.'),
('Faisal Mosque', 'SKU004.jpg','Faisal Mosque, Islamabad ke Margalla Hills ke foothills me waqia, Pakistan ki sab se bari aur modern Islamic architecture ki misaal hai. Turkish architect Vedat Dalokay ne is mosque ko design kiya jo traditional dome design se mukhtalif hai aur aik contemporary tent-shaped structure hai. Bara prayer hall, courtyard aur towering minarets hazaron worshippers ko accommodate karte hain. Manzar, gardens aur panoramic view isay tourist, photographer aur worshippers ke liye popular banate hain. Faisal Mosque Pakistan ka aik national icon hai jo religious devotion aur cultural pride ko reflect karta hai.'),
('Mazar-e-Quaid', 'SKU005.jpg','Mazar-e-Quaid, Karachi me waqia, Pakistan ke founder Quaid-e-Azam Muhammad Ali Jinnah ka final resting place hai. Yeh white marble me bana hai aur design me simple lekin dignified hai, jo Quaid ki shakhsiyat aur vision ko reflect karta hai. Bagh, fountains aur pathways yahan ki peaceful environment me izafa karte hain. Visitors, dignitaries aur tourists yahan aate hain taake Pakistan ki tareekh samjhein aur leadership, patriotism aur integrity ki ahmiyat ko mehsoos karein. Mazar-e-Quaid Pakistan ke national pride aur respect ki symbol hai.'),
('Pakistan Monument', 'SKU006.jpg','Pakistan Monument, Islamabad me waqia, chaar provinces ki unity ko symbol karta hai. Har petal Punjab, Sindh, Balochistan aur Khyber Pakhtunkhwa ko represent karta hai. Monument ke gird beautiful terrace aur panoramic city view hai. Museum me Pakistan ke culture, history aur achievements dikhaye gaye hain. Yeh monument modern symbol hai national pride aur cultural harmony ka, aur har visitor ko educate aur inspire karta hai.');

INSERT INTO northern_areas (name, image, para) VALUES
('Hunza Valley', 'SKU007.jpg', 'Hunza Valley Pakistan ka woh haseen ilaqa hai jise duniya bhar ke travelers “Heaven on Earth” ke title se pehchante hain. Yeh wadi apne buland, barf se dhakay hue paharon, neele aasman, aur bilkul saaf sheeshe jaise nadiyon ke liye mashhoor hai. Yahan ke log bohot zyada mehmaan-nawaz, sakoon-pasand aur lambe arsay tak zinda rehne wale hote hain, jiski wajah unki organic diet aur pollution-free environment hai. Hunza ke dono puranay qile—Baltit Fort aur Altit Fort—Mughal aur Tibetan style architecture ka behtareen mel hain, jo is ilaqay ke teetar-bater tareekh ko zinda rakhte hain. Spring me cherry blossom Hunza ko aik rangon ka carpet bana dete hain, jabke autumn ka mausam poori wadi ko golden aur red shades se bhar deta hai, jisay dekhne log specially foreign tours plan karte hain. Rakaposhi View Point, Eagle’s Nest aur Attabad Lake woh jagahain hain jahan khaali beth kar hawaon ki awaz sunne se bhi rooh ko sukoon milta hai. Hunza adventure lovers, nature photographers, families, honeymoon couples — sab ke liye aik complete paradise hai. Yeh wadi har season me aik nayi kahani sunati hai jo dekhne wale ko hamesha wapas bulati rehti hai.'),
('Skardu', 'SKU008.jpg', 'Skardu Gilgit-Baltistan ka sabse zyada adventure-rich region hai jahan se duniya ke chand sabse unchay paharon, including K2, ka safar shuru hota hai. Is ilaqay ke raw, untouched, aur dramatic landscapes nature ki asli taqat ka ehsaas dilate hain. Skardu Lake, Shangrila Resort, aur Upper Kachura Lake is region ke woh naqsh hain jo dekhne walon ko hamesha yaad rehte hain. Un lakes ka neela rang, unka sheer calmness aur un kay irgird phailay hue jungle aur pahad aik tasvir banate hain jo dil me bas jati hai.'),
('Naran Kaghan', 'SKU009.jpg', 'Naran Kaghan Pakistan ka sabse accessible aur sabse zyada tourist-friendly northern area hai. Yeh wadi apni lush green meadows, barf barf se dhakey hue peaks, aur tezi se behne wali nadiyon ke liye mashhoor hai. Naran ka central bazaar hamesha zinda rehta hai jahan log trout fish, warm coffee aur local handmade items enjoy karte hain. Lake Saif-ul-Malook, jo yahan ki jaan aur identity hai, aik magical jheel hai jiske bare me purani romantic kahaniyan bhi mashhoor hain. Iski green-blue waters aur aas paas ke pahadon ki reflection itni khoobsurat hoti hai ke dekh kar dil khush ho jata hai. Babusar Top tak ka safar aik adventure ride hota hai jo har mod par aik nayi beauty show karta hai. Summer me yahan ka mausam bohot pleasant hota hai jabke winters me sari wadi barf se dhak jati hai, aur roads band ho jati hain. River Kunhar ka pani itna thanda aur transparent hota hai ke usme haath dalne se bhi lagta hai jaise baraf ko chhua ho. Naran Kaghan couples, families, explorers aur photographers sab ka favourite destination hai jahan har shakhs ko natural beauty aur sakoon dono milta hai.'),
('Fairy Meadows', 'SKU010.jpg', 'Fairy Meadows duniya ke sabse khoobsurat green meadows me se aik hai jahan pohanchna thoda mushkil hai, magar wahan ka nazara har mushkil ko asaan bana deta hai. Yeh lush green plateau directly Nanga Parbat — the Killer Mountain — ka unobstructed view deta hai. Early morning me jab dhoop pahadon ke upar padti hai to poora mountain golden ho jata hai, aur yeh scene zindagi bhar bhoolne wala nahi hota. Fairy Meadows tak jeep track aur trekking ka safar aik proper adventure journey hai jo nature lovers ko aur bhi excite karta hai. Yahan ke wooden huts, deep forests aur bilkul silent nights insaan ko modern duniya ke noise se bilkul alag kar deti hain. Raat ko aasman itna clear hota hai ke Milky Way seedha aankhon ke saamne chamakti nazar aati hai — professional photography ka dream spot. Fairy Meadows ke locals simple aur friendly hote hain, aur unka culture travelers ko ek unique experience deta hai. Yeh jagah solo travelers, trekkers, wildlife lovers aur photographers sab ka favourite heaven hai.'),
('Swat Valley', 'SKU011.jpg', 'Swat Valley ko “Switzerland of Pakistan” isliye kaha jata hai kyunke yeh wadi baraf, meadows, forests, rivers aur waterfalls ka perfect combination rakhti hai. Kalam aur Ushu Forests ka green landscape, Malam Jabba ka ski resort, aur Bahrain ki flowing river tourists ke liye ideal destination create karte hain. Swat ka pani itna transparent aur fresh hota hai ke bridges se neeche ka riverbed bhi clearly nazar aata hai. Summer me yahan ka weather moderate hota hai jabke winter me pure pahad barf ki chadar odh lete hain. Swat ki history bhi bohot purani hai — yahan Buddhist civilization ke mazboot nishan, stupas aur monuments miltay hain. Mingora ka White Palace aur Malam Jabba ka sunrise views dekhne wala hamesha wapas ana chahta hai. Swat ki beauty isliye alag lagti hai kyunke yahan har dusre turn par aik nayi waterfall, naya landscape aur nayi scenic spot mil jata hai. Yeh valley families, adventurers, photographers aur nature lovers sab ke liye aik all-rounder paradise hai.'),
('Gilgit Valley', 'SKU012.jpg', 'Gilgit Valley northern Pakistan ka darwaza maana jata hai, jahan se Karakoram Highway guzar kar China tak jata hai. Gilgit ka environment bohot peaceful aur calm hota hai, jahan logon ki friendliness aur hospitality is region ko aur bhi charming banati hai. Valley ke aas paas ke pahad, flowing Gilgit River aur traditional wooden bridges aik postcard-like scene create karte hain. Gilgit ka culture centuries purana hai aur yahan ke seasonal festivals tourists ko bohot attract karte hain. Nearby attractions jaise Kargah Buddha, Gilgit Fort aur suspension bridges region ke historical importance ko highlight karte hain. Autumn me Gilgit ka rang badal jata hai jab poore valley me golden aur red shades fail jate hain. Gilgit se Skardu, Hunza aur Ghizer jaise top destinations access hotay hain, isliye yeh hub bhi kaha jata hai. Valley ka fresh air, mountains aur natural silence insaan ki mental peace ko fresh kar dete hain.'),
('Chitral', 'SKU013.jpg', 'Chitral Pakistan ka cultural jewel hai jahan majestic Tirich Mir — Hindu Kush ka sabse uncha peak — sky ke saath milta hua lagta hai. Yeh valley sirf beautiful hi nahi balkay bohot unique bhi hai kyunke yahan famous Kalash tribe rehti hai. Kalash logon ke rang birangay dresses, dance festivals, music aur ancient traditions dekhne walon ko aik nayi duniya me le jaate hain. Unke teen main festivals — Joshi, Uchal, aur Choimus — dunia bhar se log dekhne aate hain. Chitral ka weather throughout the year pleasant rehta hai, aur wadi me flowing Chitral River pure landscape ko alive rakhta hai. Old mosques, wooden architecture, aur historic forts is area ke ghair-mamooli past ko reflect karte hain. Chitral Gol National Park wildlife ka home hai jahan snow leopards, ibex aur rare species paye jate hain. Yeh jagah un travelers ke liye perfect hai jo culture + nature dono ko explore karna chahte hain.'),
('Murree', 'SKU014.jpg', 'Murree Pakistan ka sabse famous hill station hai jo Rawalpindi/Islamabad se bohot aasani se access hota hai. Pine forests, thandi hawa, hilltop cafes aur scenic viewpoints isay har season me charming banate hain. Garmi ke days me families yahan heat se bachne ke liye aati hain jabke winter me Murree aik snow paradise ban jata hai. Mall Road ka lively environment, cable cars, aur chai kay hotels har tourist ko ek relaxing experience dete hain. Pindi Point, Ayubia, Chairlift, Bhurban aur Patriata (New Murree) वो spots hain jahan insaan aik din me bhi poora adventure feel kar leta hai. Snowfall ke time Murree ki roads, hotels aur trees aik European-style winter wonderland ka scene banate hain. Murree beginner travelers, families aur couples ka favourite destination hai kyunke yahan nature, food aur comfort teeno aik hi jagah mil jate hain.'),
('Shogran', 'SKU015.jpg', 'Shogran, Pakistan ke northern areas me, specifically Kaghan Valley ka ek khubsurat hill station hai. Ye jagah apni lush green meadows aur mountains ke liye mashhoor hai. Shogran ka area dense forests aur pine trees se ghira hua hai, jo isse nature lovers aur photographers ke liye ek perfect destination banata hai. Yahan ki scenery har season me alag lagti hai; summer me yeh area vibrant green aur fresh rehta hai, jabke winter me ye snow se dhak jata hai aur ek snowy wonderland me tabdeel ho jata hai. Tourists ke liye Shogran ek ideal spot hai hiking aur trekking ke liye. Yahan se nearby places jaise Siri Paye, Lalazar aur Makra Peak easily accessible hain. Hiking trails aur walking paths nature ke saath interact karne ka mauka dete hain. Local culture aur hospitality bhi yahan ka ek special attraction hai. Shogran ke locals bohot friendly aur helpful hain, aur traditional Pashtun aur Hindko culture ka blend yahan nazar aata hai.');
